- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-cover:
            voting: false

    gate:
      jobs:
        - openstack-tox-lower-constraints
